### PR TITLE
test: ADDON-64637 add tests for InputPage and MenuInput

### PR DESCRIPTION
**Pull request by vtsvetkov-splunk**
The JIRA link - https://splunk.atlassian.net/browse/ADDON-64637

Added unit/integration tests MenuInput and InputPage components.

I have question about the following functionality:
[CustomMenu.jsx:22](https://github.com/splunk/addonfactory-ucc-base-ui/blob/f40b95de8aa868cf3bdb87208eb0827d93753ee7/src/main/webapp/components/CustomMenu.jsx#L22)
```ts
if (services && customMenuField && !groupsMenu) {
    customControl.render();
}
```
we don't render custom component if we don't have groupsMenu.

It is covered with test: `should render CustomMenu wrapper with groupsMenu without rendering underlying custom component`

### CODE REVIEW

**Comment by tbalar-splunk** [comment]
[CustomMenu](https://splunk.github.io/addonfactory-ucc-generator/custom_ui_extensions/custom_menu/) and [GroupsMenu](https://splunk.github.io/addonfactory-ucc-generator/inputs/multilevel_menu/) are separate elements with unique characteristics. It’s important to note that only one of these features, either 'CustomMenu' or 'GroupsMenu' can be used at a time. This necessity for exclusivity is precisely why a conditional statement is implemented within the code.

**Comment by tbalar-splunk** [comment]
I think, this validation is there in the ucc-gen. (If not, we will add)
Just to safer side, we also have added that condition.

**Comment by wmazur-splunk** [comment]
>I want to hear screaming if something goes wrong 😁.
👍  for that

**Comment by tbalar-splunk** [comment]
@vtsvetkov-splunk I'm having less experience in writing test cases, and I'm uncertain about the most suitable person to assess these. However, at a high level, these test cases appear satisfactory to me. @wmazur-splunk

**Review by tbalar-splunk — APPROVED** [review]

**Comment by vtsvetkov-splunk** [comment]
@tbalar-splunk 
> **If both group and custom menus are present in the global configuration file, the custom menu takes precedence.** Nonetheless, it's crucial for us to document this information for future reference.

If you say we should show only _one_ of them, but not both, it does not play well with a code in [MenuInput.jsx:205](https://github.com/splunk/addonfactory-ucc-base-ui/blob/f40b95de8aa868cf3bdb87208eb0827d93753ee7/src/main/webapp/components/MenuInput.jsx#L205C7-L210):
```ts
// Introducing a condition to enable simultaneous support for custom menu src and Groups Menu.
// ADDON-62948
if (services && customMenuField?.src && groupsMenu) {
    return getCustomMenuAndGroupsMenu();
} 
```
Seems like we do show both of them in one file (MenuInput), but cut it in another (CustomMenu). I wish to document it, but it is not clear for me how it is supposed to work. 

Alright, I don't want you to dig into old code and try to recall everything. I will try to find out later, because I debug it only with tests and see only HTML markdown without UI.

**Pull request merged**
