### PR TITLE
fix: ADDON-61204 Remove support of placeholder property

### PR DESCRIPTION
**Pull request by tbalar-splunk**
**Jira Link -** https://splunk.atlassian.net/browse/ADDON-61204

We have deprecated support for the "placeholder" attribute (as announced by Splunk UI.) It won't be breaking change.

Users can still use the "placeholder" property in the global config file, but it won't have any impact on the UI. As a result, the placeholder will not be visible anymore. Instead of that, we recommend using the [help](https://splunk.github.io/addonfactory-ucc-generator/entity/) property to display any additional message along with the component.

Slack thread link for ref - https://splunk.slack.com/archives/C8R00E97S/p1689831102691599

### CODE REVIEW

**Review by wmazur-splunk — DISMISSED** [review]

**Review by vtsvetkov-splunk — DISMISSED** [review]
LGTM

**Comment by artemrys** [comment]
@tbalar-splunk Please rebase the PR as it has conflicts with main.

**Comment by vtsvetkov-splunk** [comment]
> Users can still use the "placeholder" property in the global config file, but it won't have any impact on the UI. As a result, the placeholder will not be visible anymore.

I did not get that point. Why should we keep it in schema.json?

**Comment by tbalar-splunk** [comment]
We want to ensure that we don't disrupt any existing TA, so we have included a placeholder in the schema file. Removing it would be a breaking change. Therefore, we are currently marking the placeholder property as deprecated. We plan to remove support for it in the UCC once Splunk UI stops supporting it.

**Comment by vtsvetkov-splunk** [comment]
@tbalar-splunk 
This is what I see, maybe I miss the context of the decision that already made.
Users have placeholder in config file and they expect to see it. Here we introduce breaking changes, but hiding them from users, don't we.

**Comment by tbalar-splunk** [comment]
We have decided to show warning (deprecate) message if placeholder is available in the global config file. I think, @artemrys has added the same?

**Review by vtsvetkov-splunk — APPROVED** [review]

**Pull request merged**
