### PR TITLE
fix: ADDON-64637 add input value to query for menu navigation

### PR DESCRIPTION
**Pull request by vtsvetkov-splunk**
The JIRA Link: [ADDON-64637](https://splunk.atlassian.net/browse/ADDON-64637)

I have changed the argument of `handleRequestOpen` prop of MenuInput from
```ts
handleRequestOpen(serviceName: string, groupName: string);
```
to
```ts
handleRequestOpen(params: { serviceName: string, groupName?: string, input?: string });
```

The input value is required in InputPage component for setting URL QueryParam

### input with group
image
image
 
image

### input without group
image

### CODE REVIEW

**Comment by tbalar-splunk** [comment]
After updating this code we have make sure that the existing functionality should work as expected - **When groups are not present in the global config file**
This will be done by setting **style:page** in the global config file.

**Comment by vtsvetkov-splunk** [comment]
@tbalar-splunk 
I added screenshots.

> After updating this code we have make sure that the existing functionality should work as expected - **When groups are not present in the global config file** This will be done by setting **style:page** in the global config file.

That is why I added tests first. By seeing changes in test cases we may see what has changed.
I am going to spin up the e2e tests from backend repo to check if they are passing

**Review by tbalar-splunk — APPROVED** [review]

**Comment by vtsvetkov-splunk** [comment]
I made it work
image

**Pull request merged**
