### PR TITLE
chore: ignore license header check on THIRDPARTY (notice) file

### PR DESCRIPTION
**Pull request by harshpatel-crest**

### CODE REVIEW

**Comment by harshpatel-crest** [comment]
@rfaircloth-splunk The snyk is failing due to `snyk.sarif` not found error. Do you know what could be the reason?

**Comment by arys-splunk** [comment]
@harshpatel-crest PTAL at a PR that is fixing `snyk.sarif` in `addonfactory-ucc-generator`: https://github.com/splunk/addonfactory-ucc-generator/commit/d5c544272a52d774b728b168cdf69efb512d1782

**Comment by harshpatel-crest** [comment]
@arys-splunk Thanks!

**Review by arys-splunk — APPROVED** [review]

**Pull request merged**
