### PR TITLE
feat: add configurability for actions from `globalConfig.json`

### PR DESCRIPTION
**Pull request by harshpatel-crest**
Jira: https://jira.splunk.com/browse/ADDON-40214

Note: `enable` action is deprecated so we might need to add follow up PR in `ucc-gen` for this change. Also, `actions` were not working before so some TAs might update their UI after this change which needs to be highlighted by maybe breaking change commit in `ucc-gen`?

### CODE REVIEW

**Review by dhruvanshus-crest — APPROVED** [review]

**Review by dkhatri-crest — APPROVED** [review]

**Review by mchavda-splunk — APPROVED** [review]
If it's going to affect existing TAs then we should highlight it as a breaking change.

**Comment by harshpatel-crest** [comment]
Fixes https://github.com/splunk/addonfactory-ucc-base-ui/issues/74

**Comment by arys-splunk** [comment]
@harshpatel-crest Should we have `ucc-gen` do the automation around changing `enable` to `add`? Some of the add-ons have `enable` in their `globalConfig.json`. Github search: https://github.com/search?q=org%3Asplunk+path%3A%2F+filename%3AglobalConfig.json+enable (it's not ideal search, but gives a rough idea).

**Comment by harshpatel-crest** [comment]
@arys-splunk We will need to automate adding all actions in the actions config upon upgrade as existing behaviour is to allow all actions. I removed "enable" from schema because enable actions is referring basically to the column "status" and users can remove this column from `globalConfig` if they want to disallow users from seeing enable/disable toggle.

**Comment by artemrys** [comment]
Done in #239

**Pull request closed without merging**
