### PR TITLE
ci: add job for running ci tests

### PR DESCRIPTION
**Pull request by vtsvetkov-splunk**
PR adds ability to run e2e tests from the [addonfactory-ucc-generator](https://github.com/splunk/addonfactory-ucc-generator) repository

### CODE REVIEW

**Comment by wmazur-splunk** [comment]
@artemrys : not in this PR :-) But feel free to add Jira task for that

**Review by vtsvetkov-splunk — COMMENTED** [review]
@artemrys I am ok with merging this repo to the main repo. 
I don't see that this CI job would make any harm. Of course, it will be removed, but we don't have it even planned yet? Until that moment, we can utilize the help of written tests.

**Comment by artemrys** [comment]
> @artemrys I am ok with merging this repo to the main repo. I don't see that this CI job would make any harm. Of course, it will be removed, but we don't have it even planned yet? Until that moment, we can utilize the help of written tests.

Okay, let's live like that for now, we will plan this move for the next Q.

**Review by artemrys — APPROVED** [review]

**Pull request merged**
